services:
  apache:
    build: "./php"
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - "./:/var/www/html:ro"
      - "./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro"
    networks:
      - novel-network

networks:
  novel-network: