; system
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
max_input_time = 300

; display errors
display_errors = On
display_startup_errors = ${PHP_DISPLAY_ERRORS}
error_reporting = E_ALL

; logging
log_errors = On
error_log = /var/log/php_errors.log

; timezone
date.timezone = Europe/Moscow

; session
session.gc_maxlifetime = 1440
session.cookie_lifetime = 0
session.cookie_secure = 0
session.cookie_httponly = 1